name: Reusable workflow example

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "Running Reusable Workflow"
      - id: step2
        run: exit 1
